HTML_EXTRACTOR_NODE = "html_extractor"
KEYWORDS_EXTRACTOR_NODE = "keywords_extractor"
QNA_EXTRACTOR_NODE = "qna_extractor"
IOCS_EXTRACTOR_NODE = "iocs_extractor"
TRAM_CLASSIFIER_NODE = "tram_classifier"